---
- name: 01-cluster.conf for htcondor
  template:
    src: 01-cluster.conf.j2
    dest: /etc/condor/config.d/01-cluster.conf
  notify: restart condor
- name: 02-local.conf for htcondor
  template:
    src: 02-local.conf.j2
    dest: /etc/condor/config.d/02-local.conf
  notify: restart condor
- name: Check Pool password file
  stat:
    path: "{{ condor_pool_password_file_path }}"
  register: stat_result
- name: Create Pool Password
  command: "condor_store_cred -f {{ condor_pool_password_file_path }}"
  args:
    stdin: "{{ condor_pool_password }}"
  notify: generate daemon idtoken
  when: not stat_result.stat.exists
- name: Check password file's owner and group
  file:
    path: "{{ condor_pool_password_file_path }}"
    owner: root
    group: root
- name: Starting the condor service.
  service:
    name: condor
    state: started
    enabled: true
